apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/TODO_BACKEND_IMAGE
          env:
            - name: PORT
              value: "3000"
            - name: POSTGRES_HOST
              value: todo-backend-postgres-svc
            - name: POSTGRES_PORT
              value: "5432"
          envFrom:
            - secretRef:
                name: todo-backend-postgres-credentials
