apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: todo-app-image-claim
      containers:
        - name: todo-app
          image: todo-app:2.5
          envFrom:
            - configMapRef:
                name: todo-app-config
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
          volumeMounts:
            - name: image-cache
              mountPath: /usr/src/app/images
