apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JJnne/devops-with-kubernetes-2026.git
    targetRevision: main
    path: project
  destination:
    server: https://kubernetes.default.svc
    namespace: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
