apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: exercises
data:
    POSTGRES_USER: ENC[AES256_GCM,data:d37OoMl2TO8=,iv:qxFVblTzRmF1J8PL8dzNDiGYDzOwURggBnlJ+BL3LQM=,tag:AqGUiOLck7IaPlw+JnVV5Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3eOf8jg2rOnpsTiHhGn5xykdjuUvxerwF7HxcaX7/I8=,iv:heLSchK98w0W11MEjavi/H7UMHbPSBNdccCiw5KzbIk=,tag:aZHCSZIS4ofLVxhu42IUAQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:mWovzELkRJD79Sy4DlMBsSWsQ2Js0esq,iv:wZLFCtr2OtcqBNQbnaCzKHvu35Ih+YtjMIeneVndhRU=,tag:ohSPEICLB+msE7BKTmwJjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVHM2RmpCRFlpNXZEdjhT
            cHd6bkRpOHRpWk5Td1VRV2Z3MGE2ZGJuWEFZCm5ac3VqNmRXTVc0ckhFcHh3UTR1
            WURXRVh2ZkVmcWpUWlhJVTNQQlY5QWMKLS0tIHdwYWJVcTY3N25rVmRNYzhUTjRG
            ODVvbG9TWGFnVS9tVzcvZWFwWUJxSncKKFbnrn22pZUNo0mcSWVpjQh0MqIGKUNP
            bgVkW2TSn/Qqp3ookOY2XLNBxb47PaWHDHDp0s5tRPh/pEXTZUpmGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14qm4lq7kj2f4n29rskcqyeghund5ynfjguf20z3mpqfqp2sw7yks04f6yt
    encrypted_regex: ^(data)$
    lastmodified: "2026-07-05T13:40:33Z"
    mac: ENC[AES256_GCM,data:C2kjFYzOkxdodd7N9okDPJkAMpwCICOffS7vWBkkPVibxoHV4YtXmYHMoC1rbjo3hbi9cNs/3D1OOXzXWpfx+hXNGWDFl1af7f9JGqGbjpch9ulWRnPBqjfgMTFdYZ8dfkMNt/e+dxa+6jrxEH5ljh8rEcEPACBUoEY9lFswVyQ=,iv:/Qy1wbgSfVM6nOELBRwRaX8AKsHBUQXOxQRQPICqEp0=,tag:FBQSp2F2lnDnL8D2AYMOaQ==,type:str]
    version: 3.13.2
