apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-reminder-cronjob
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-reminder
              image: curlimages/curl:latest
              command:
                - sh
                - -c
                - |
                  URL=$(curl -s -o /dev/null -w '%{redirect_url}' https://en.wikipedia.org/wiki/Special:Random)
                  curl -s -X POST -H "Content-Type: application/json" -d "{\"content\":\"Read $URL\"}" http://todo-backend-svc:2345/todos
              resources:
                requests:
                  cpu: "10m"
                  memory: "16Mi"
                limits:
                  cpu: "50m"
                  memory: "32Mi"
          restartPolicy: Never
