apiVersion: v1
kind: Secret
metadata:
    name: todo-backend-postgres-credentials
    namespace: project
data:
    POSTGRES_USER: ENC[AES256_GCM,data:WsfUHNQ5tfA=,iv:3BqCqPHkZEyA4b075Hd35uXUYNrvqgWjFCoeZWQ4Oy0=,tag:RJwVsj0M3VsMje1AUSiTng==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:fOFBITGmAmZhFJ5j2/Z2mEYAys5Vcks4Xh4xYzqF7NQ=,iv:OnEFObjWk3qFrCW3bb1qFsTdWpCXhfJt9tXpQ/NoMaE=,tag:g4eUN/DnWfUELCdbURZysg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:ntE7EspYlGM=,iv:zfZfMtd2Ke+wdapdRs9Gafm2Q25RzAZWeB9237acdyA=,tag:6jatpfN65uN1HRHZRt0C3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZkFvOGhKWlREa1Bmdmkw
            bHFLeTZQM1NUb2hrTEFYakpHMFM0aEZqdTA4CldWdG82cGJrRjU3RU9kSFp1emcz
            cExiVUJKbzhFNFhjZzhna0dYRHhFRVkKLS0tIEFQeThDUFJtcktFbUZldHNHYXJl
            VkM3QWxjSWpSRElIalRyNTBQU2NoZDQKkLJ5bc6xkfcdsujkaz5z3ls71K4FfcHm
            hRZS6dkpwhuJVxMYRfqKY5RgqxdNs/PvKZAR+eRHPc/y3RCid0XODg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14qm4lq7kj2f4n29rskcqyeghund5ynfjguf20z3mpqfqp2sw7yks04f6yt
    encrypted_regex: ^(data)$
    lastmodified: "2026-07-05T14:03:11Z"
    mac: ENC[AES256_GCM,data:oQfgpRMHkkB7DIXJRLGIZ3AgbIGoKMOuvcUjCmqwL+9hP3V3ldzqikoDAs7YO8CP/zrKO0fvLchXYB4SQKE3AWonrndEfUl0rRpgG4SmzqPedyEcdRXZmU384I/Ihxmxtg+SF2iFhjhqDnhsK1Dj/T34nFxphrgPpQaW9GSXTCw=,iv:8FoDJqnZcxui2iCCstEP4NH1VxeQ9ufAE1Hipreha/w=,tag:iTwJgtH9cNkQQU4jWHRlxQ==,type:str]
    version: 3.13.2
