apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-image-claim
spec:
  storageClassName: todo-app-image-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
